"""add catatan to food data

Revision ID: 8100e007209e
Revises: bc10cf5a949a
Create Date: 2026-04-17 01:45:30.291390
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8100e007209e'
down_revision = 'bc10cf5a949a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_data', sa.Column('catatan', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food_data', 'catatan')
    # ### end Alembic commands ###
