"""init schema

Revision ID: bc10cf5a949a
Revises: 
Create Date: 2026-04-17 01:37:28.440816
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc10cf5a949a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'food_data',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('bulan', sa.Integer(), nullable=True),
        sa.Column('tahun', sa.Integer(), nullable=True),
        sa.Column('beras_tersedia', sa.Float(), nullable=False),
        sa.Column('beras_kebutuhan', sa.Float(), nullable=False),
        sa.Column('minyak_tersedia', sa.Float(), nullable=False),
        sa.Column('minyak_kebutuhan', sa.Float(), nullable=False),
        sa.Column('telur_tersedia', sa.Float(), nullable=False),
        sa.Column('telur_kebutuhan', sa.Float(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_food_data_id', 'food_data', ['id'], unique=False)
    op.create_table(
        'prediction_results',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('food_data_id', sa.Integer(), nullable=False),
        sa.Column('beras_ratio', sa.Float(), nullable=False),
        sa.Column('minyak_ratio', sa.Float(), nullable=False),
        sa.Column('telur_ratio', sa.Float(), nullable=False),
        sa.Column('hasil_prediksi', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['food_data_id'], ['food_data.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('food_data_id')
    )
    op.create_index('ix_prediction_results_hasil_prediksi', 'prediction_results', ['hasil_prediksi'], unique=False)
    op.create_index('ix_prediction_results_id', 'prediction_results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_prediction_results_id', table_name='prediction_results')
    op.drop_index('ix_prediction_results_hasil_prediksi', table_name='prediction_results')
    op.drop_table('prediction_results')
    op.drop_index('ix_food_data_id', table_name='food_data')
    op.drop_table('food_data')
    # ### end Alembic commands ###
